package ventanas.paneles;

import clases.Conectar;
import clases.PlaceHonder;
import clases.Validar;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import componentesVisuales.TextFieldRedondeado;
import ventanas.Login;


/**
 *
 * @author Carlos
 */
public class RegistrarCliente extends javax.swing.JPanel {

    List<TextFieldRedondeado> elementos = new ArrayList<>();

    String user;

    public RegistrarCliente() {
        initComponents();
        llenarElementos();
        user = Login.user;
    }

    private void llenarElementos() {
        elementos.add(txtNombre);
        elementos.add(txtCedula);
        elementos.add(txtCorreo);
        elementos.add(dirreccion);
        elementos.add(txtTelefono);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new componentesVisuales.TextFieldRedondeado();
        txtCedula = new componentesVisuales.TextFieldRedondeado();
        txtCorreo = new componentesVisuales.TextFieldRedondeado();
        txtTelefono = new componentesVisuales.TextFieldRedondeado();
        dirreccion = new componentesVisuales.TextFieldRedondeado();
        labelAltaDefinicion1 = new componentesVisuales.LabelAltaDefinicion();
        registrarClient = new componentesVisuales.PanelRedondeado();
        lregistrarC = new componentesVisuales.LabelRedondeada();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setForeground(new java.awt.Color(153, 153, 153));
        txtNombre.setText("Ingrese el Nombre");
        txtNombre.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtNombre.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/2user24.png"))); // NOI18N
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 380, 80));

        txtCedula.setForeground(new java.awt.Color(153, 153, 153));
        txtCedula.setText("Ingrese la Cedula");
        txtCedula.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtCedula.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/id24.png"))); // NOI18N
        txtCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCedulaMousePressed(evt);
            }
        });
        add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 380, 80));

        txtCorreo.setForeground(new java.awt.Color(153, 153, 153));
        txtCorreo.setText("Ingrese el Correo");
        txtCorreo.setToolTipText("");
        txtCorreo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtCorreo.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/email24.png"))); // NOI18N
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });
        add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 380, 80));

        txtTelefono.setForeground(new java.awt.Color(153, 153, 153));
        txtTelefono.setText("Ingrese el Telefono");
        txtTelefono.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtTelefono.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/phone24.png"))); // NOI18N
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoMousePressed(evt);
            }
        });
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 380, 80));

        dirreccion.setForeground(new java.awt.Color(153, 153, 153));
        dirreccion.setText("Ingrese su Direccion");
        dirreccion.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        dirreccion.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/map.png"))); // NOI18N
        dirreccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dirreccionMousePressed(evt);
            }
        });
        add(dirreccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 380, 80));

        labelAltaDefinicion1.setForeground(new java.awt.Color(51, 51, 51));
        labelAltaDefinicion1.setText("Registros de Clientes");
        labelAltaDefinicion1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        add(labelAltaDefinicion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 290, 40));

        registrarClient.setBackground(new java.awt.Color(0, 73, 173));
        registrarClient.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lregistrarC.setForeground(new java.awt.Color(255, 255, 255));
        lregistrarC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lregistrarC.setText("REGISTRAR CLIENTE");
        lregistrarC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lregistrarC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lregistrarC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lregistrarCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lregistrarCMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lregistrarCMousePressed(evt);
            }
        });
        registrarClient.add(lregistrarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 80));

        add(registrarClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, 380, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void lregistrarCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lregistrarCMouseEntered
        registrarClient.setBackground(new Color(3, 88, 202));
    }//GEN-LAST:event_lregistrarCMouseEntered

    private void lregistrarCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lregistrarCMouseExited
        registrarClient.setBackground(new Color(0, 74, 173));
    }//GEN-LAST:event_lregistrarCMouseExited

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
        PlaceHonder.placeHolderClientes(elementos, 1);
    }//GEN-LAST:event_txtNombreMousePressed

    private void txtCedulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedulaMousePressed
        PlaceHonder.placeHolderClientes(elementos, 2);
    }//GEN-LAST:event_txtCedulaMousePressed

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
       PlaceHonder.placeHolderClientes(elementos, 3);
    }//GEN-LAST:event_txtCorreoMousePressed

    private void dirreccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dirreccionMousePressed
        PlaceHonder.placeHolderClientes(elementos, 4);
    }//GEN-LAST:event_dirreccionMousePressed

    private void txtTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMousePressed
        PlaceHonder.placeHolderClientes(elementos, 5);
    }//GEN-LAST:event_txtTelefonoMousePressed

    private void lregistrarCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lregistrarCMousePressed

        if (Validar.validarClientes(elementos)) {
            String nombre = txtNombre.getText().trim();
            String cedula = txtCedula.getText().trim();
            String correo = txtCorreo.getText().trim();
            String telefono = txtTelefono.getText().trim();
            String direccion = dirreccion.getText().trim();
            user = Login.user;
            
            try {
                Connection cn = new Conectar().conectar();
                PreparedStatement ps = cn.prepareStatement(
                        "insert into clientes values(?,?,?,?,?,?)");
                ps.setString(1, nombre);
                ps.setString(2, cedula);
                ps.setString(3, correo);
                ps.setString(4, telefono);
                ps.setString(5, direccion);
                ps.setString(6, user);

                int resultado = ps.executeUpdate();
                if (resultado > 0) {
                    JOptionPane.showMessageDialog(null, "Exitoso");
                }

                limpiar();

            } catch (HeadlessException | SQLException e) {
                System.out.println("Error en Registrar cliente: " + e);
            }
            
        }
    }//GEN-LAST:event_lregistrarCMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentesVisuales.TextFieldRedondeado dirreccion;
    private componentesVisuales.LabelAltaDefinicion labelAltaDefinicion1;
    private componentesVisuales.LabelRedondeada lregistrarC;
    private componentesVisuales.PanelRedondeado registrarClient;
    private componentesVisuales.TextFieldRedondeado txtCedula;
    private componentesVisuales.TextFieldRedondeado txtCorreo;
    private componentesVisuales.TextFieldRedondeado txtNombre;
    private componentesVisuales.TextFieldRedondeado txtTelefono;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
        txtNombre.setForeground(new Color(153, 153, 153));
        txtCedula.setForeground(new Color(153, 153, 153));
        txtCorreo.setForeground(new Color(153, 153, 153));
        txtTelefono.setForeground(new Color(153, 153, 153));
        dirreccion.setForeground(new Color(153, 153, 153));

        dirreccion.setText("Ingrese su Direccion");
        txtNombre.setText("Ingrese el Nombre");
        txtCedula.setText("Ingrese la Cedula");
        txtCorreo.setText("Ingrese el Correo");
        txtTelefono.setText("Ingrese el Telefono");

    }
}
